Repository akka/akka-projection, pull requests merged in 2020-07, with the labels that each got.

#331 Use the proper offset handler in each tests
  akka-projection-core/src/test/scala/akka/projection/internal/metrics/ErrorRateMetricSpec.scala
Labels: bug

#330 Observer/telemetry: progress reports iff offset has been committed
  akka-projection-core/src/main/scala/akka/projection/StatusObserver.scala
  akka-projection-core/src/main/scala/akka/projection/internal/InternalProjectionState.scala
  akka-projection-core/src/main/scala/akka/projection/internal/NoopStatusObserver.scala
  akka-projection-core/src/test/scala/akka/projection/TestStatusObserver.scala
  akka-projection-jdbc/src/test/scala/akka/projection/jdbc/JdbcProjectionSpec.scala
Labels: enhancement

#360 A note on idempotence
  docs/src/main/paradox/cassandra.md
  docs/src/main/paradox/jdbc.md
  docs/src/main/paradox/slick.md
Labels: documentation

#364 Remove unused Executioncontexts
  examples/src/test/scala/docs/jdbc/JdbcProjectionDocExample.scala
Labels: documentation

#365 Add missing bit on the class name
  docs/src/main/paradox/kafka.md
Labels: documentation

#369 Document how to Alpakka Kafka Producer flow
  docs/src/main/paradox/kafka.md
  examples/src/test/java/jdocs/kafka/KafkaDocExample.java
  examples/src/test/scala/docs/kafka/KafkaDocExample.scala
Labels: documentation

#371 Use a JDBC-backed handler to demo exactly-once
  docs/src/main/paradox/kafka.md
  examples/src/test/java/jdocs/jdbc/HibernateJdbcSession.java
  examples/src/test/java/jdocs/kafka/KafkaDocExample.java
  examples/src/test/scala/docs/kafka/KafkaDocExample.scala
Labels: documentation
